server:
  port: 8081


spring:
  application:
    name: first-service

eureka:
  client:
    register-with-eureka: false
    # Eureka 서버로부터 객체의 정보를 주기적으로 가져올 것인지 속성
    # True, 갱신된 정보를 받겠다.
    fetch-registry: false